## ===----------------------------------------------------------------------===
## 
## This source file is part of the Amiibo Service open source project
## 
## Copyright (c) 2025 Röck+Cöde VoF. and the Amiibo Service project authors
## Licensed under Apache license v2.0
## 
## See LICENSE for license information
## See CONTRIBUTORS for the list of Amiibo Service project authors
##
## SPDX-License-Identifier: Apache-2.0
## 
## ===----------------------------------------------------------------------===

version: 1
external_links:
  documentation: "https://rock-n-code.github.io/amiibo-service/documentation/amiiboservice/"
